[MudaeRoller] Option to set max rolls and dk wait time.
chiyadev/MudaeFarm pull request #222
Opened 2020-09-25 07:24 UTC by Dogeek

The max rolls option will be used whenever TryParseRollLimited returns false, or mudae sends a non parsable message

DailyKakeraWaitTime will set the wait time for the $dk command (20 hours by default, 10 hours if premium mudae member)

2020-09-25 23:22 UTC, phosphene47 requested changes
Interesting PR! Other than the naming issue, this already looks good to merge.

It might also be a good idea to update the README briefly explaining what the new configurations do.

2020-09-25 23:22 UTC, phosphene47 commented on MudaeFarm/Options.cs
> +        public int GlobalMaxRolls { get; set; } = 5;
I think `GlobalMaxRolls` would be better named as `DailyKakeraDefaultRolls`. The word "global" makes it sounds like you are setting a maximum number of rolls across all configured channels, which is not the case.

2020-09-26 07:22 UTC, Dogeek commented on MudaeFarm/Options.cs
> +        public int GlobalMaxRolls { get; set; } = 5;
It is the case, if you look at the roller code, the GlobalMaxRoll option is used in place of the hard limit of 5 rolls, which, if I understood the code correctly, means that there will be at least $GlobalMaxRolls rolls done, even in case of a mudae message that the bot doesn't understand (i.e. wished characters notifications for instance)

2020-09-26 07:23 UTC, Dogeek commented
Agreed on the readme changes. Do you prefer that I amend that commit and force push on my branch, or that I make a new commit with only the readme changes ?

2020-09-26 07:44 UTC, phosphene47 commented on MudaeFarm/Options.cs
> +        public int GlobalMaxRolls { get; set; } = 5;
Sorry, I don't know why I thought this property was for daily kakeras. I checked this code while half-awake 😅.

In any case, "global" doesn't make sense to me because this is a per-channel limit. The method you edited `RunRollAsync` runs per-channel. The property is basically saying "For each channel, MudaeFarm will roll at least {this} many times, when it doesn't understand the output of a roll," which is why I chose to say "default". The property is not a hard max/min limit; it's the number of rolls MudaeFarm assumes when it doesn't detect Mudae saying "you are on cooldown!"

I think `DefaultPerHour` (`default_per_hour`) would be good. What do you think?

2020-09-26 07:45 UTC, phosphene47 commented
New commit would be good. Force pushing should always be avoided if possible.

2020-09-26 07:56 UTC, phosphene47 requested changes
After more inspection, I found other problems with this PR.

2020-09-26 07:56 UTC, phosphene47 commented on MudaeFarm/Options.cs
> +        public int DailyKakeraWaitTime { get; set; } = 20;
There is a naming convention of configuration classes to specify the unit in property names to avoid confusion. This should be `DailyKakeraWaitHours`.

2020-09-26 07:56 UTC, phosphene47 commented on MudaeFarm/MudaeRoller.cs
> +                else if (response.Content.StartsWith("wished by", StringComparison.OrdinalIgnoreCase))
Is this necessary? I don't think this branch will ever be taken, because AFAIK Mudae doesn't say "wished by" without a character embed (the loop is always continued if there is an embed, check above code.)

If I understand your motive correctly, this was probably an attempt to circumvent https://github.com/chiyadev/MudaeFarm/issues/151. However this would only fix half of the issue, which is detecting a character that has a separate "wished by" message. I'm thinking of implementing a separate service to do that, but it would be out of scope for this PR.

2020-09-26 09:30 UTC, Dogeek commented on MudaeFarm/MudaeRoller.cs
> +                else if (response.Content.StartsWith("wished by", StringComparison.OrdinalIgnoreCase))
Well I was investigating why MudaeFarm suddenly stopped before all the rolls were complete, by looking at the logs in the console, I found out that Mudae pinged me, because I rolled a wished character. This caused the code to enter the 'if rolls > 5' condition, and thus stopping the rolls prematurely.

This can be removed though, if the user sets everything up correctly, by increasing GlobalMaxRolls

2020-09-26 09:31 UTC, Dogeek commented on MudaeFarm/Options.cs
> +        public int GlobalMaxRolls { get; set; } = 5;
DefaultPerHour works for me. I'll amend my commit right away

2020-09-26 12:05 UTC, phosphene47 approved these changes

2020-09-26 12:06 UTC, merged

2020-09-26 12:06 UTC, phosphene47 commented
Thanks!